@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

[Core] <<ArchUnit.Core.*>>
[Application] <<ArchUnit.Application.*>>
[Infra] <<ArchUnit.Infra.*>>
[Web] <<ArchUnit.Web.*>> as web
'[Products] <<ExampleTest.PlantUml.Product.*>>
'[Product Catalog] <<ExampleTest.PlantUml.Catalog.*>> as catalog

' Could be some random comment
'[XML] <<ExampleTest.PlantUml.XML.Processor.*>> <<xampleTest.PlantUml.XML.Types.*>> as xml

[Application] --> [Core]
web --> [Application]
web --> [Infra]
'
'[Addresses] --> catalog
'
'[Orders] ---> [Customers] : is placed by
'[Orders] --> [Products]
'[Orders] --> [Addresses]
'
'[Customers] -->[Addresses]
'[Customers] --> [Products]
'[Customers] --> [Orders]
'
'[Products] <--[#green]- catalog
'[Products] --> [Customers]
'[Products] --> [Orders]
'catalog --> [Orders]
'import -left-> catalog : parse products
'import --> xml
'import --> [Customers]
'note top on link #lightgreen: is responsible for translating XML to csharp classes

@enduml