@startuml

[AirClient] <<gRPC.AirClient.*>> as client
[AirServer] <<gRPC.AirServer.*>> as server
[AirStation] <<gRPC.AirStation.*>> as station

station .> server : station streaming \n(client-streaming)
server <..> client  : bi-directional streaming

@enduml